import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discuss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          <div className="flex items-center justify-center">
            <div className="w-[800px]">
              <Header />
              <div className="mt-[calc(67.2px+2rem)] px-4 pb-8">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
